### PR TITLE
Support data object toJson() methods

### PR DESCRIPTION
**Pull request by tsegismont**
Needed to support examples as the following in `vertx-config`:

```java
JsonObject vault_config = new JsonObject()
  .put("host", "127.0.0.1") // The host name
  .put("port", 8200) // The port
  .put("ssl", true); // Whether or not SSL is used (disabled by default)

// Certificates
PemKeyCertOptions certs = new PemKeyCertOptions()
  .addCertPath("target/vault/config/ssl/client-cert.pem")
  .addKeyPath("target/vault/config/ssl/client-privatekey.pem");
vault_config.put("pemKeyCertOptions", certs.toJson());

// Truststore
JksOptions jks = new JksOptions()
  .setPath("target/vault/config/ssl/truststore.jks");
vault_config.put("trustStoreOptions", jks.toJson());

// Path to the secret to read.
vault_config.put("path", "secret/my-secret");

ConfigStoreOptions store = new ConfigStoreOptions()
  .setType("vault")
  .setConfig(vault_config);

ConfigRetriever retriever = ConfigRetriever.create(vertx,
  new ConfigRetrieverOptions().addStore(store));
```

### CODE REVIEW

**Comment by vietj** [comment]
so we need this because in java script data objects don't exist and are handled natively, right ?

**Comment by tsegismont** [comment]
Neither in Ruby, I think. Anyway, that's not the reason. The reason is sometimes we need to convert options to JSON format because a module handles config dynamically.

See the example above: there are many types of config store, so one needs to provide a JSON object config. But if you're using the vault config store, you know that you can provide `pemKeyCertOptions`. So instead of creating the config manually, you create a `PemKeyCertOptions` instance, then convert it to JSON.

This Java example is taken from: https://vertx.io/docs/vertx-config/java/#_configuring_the_store_7.
It cannot be translated without this change: https://vertx.io/docs/vertx-config/js/#_configuring_the_store_7

**Comment by tsegismont** [comment]
@vietj I can rebase the PR if you're fine with the change. So what's your take on this one?

**Comment by vietj** [comment]
that would be great to have it, it wasn't on my radar anymore

**Comment by vietj** [comment]
sorry for that btw

**Comment by tsegismont** [comment]
@vietj no problem. I just rebased and the build passes on my box.

**Review by vietj — COMMENTED** [review]
ok

**Pull request merged**
