### PR TITLE
Updated kotlin version to 1.3.0

### PR DESCRIPTION
**Pull request by gmariotti**
Needed for issue https://github.com/vert-x3/vertx-lang-kotlin/issues/88

### CODE REVIEW

**Comment by gmariotti** [comment]
@vietj any update on this PR?

**Comment by vietj** [comment]
I did it directly I think

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-codetrans/commit/0a4d6a384da0f0c76234b9aad7a7ec796ebbdfa7

**Comment by gmariotti** [comment]
@vietj sorry 😓, I "obviously" looked only at the first 2 commits on master

**Pull request closed without merging**
