### PR TITLE
Fix build badge url and kotlin dependencies

### PR DESCRIPTION
**Pull request by okou19900722**

### CODE REVIEW

**Comment by vietj** [comment]
can we try to move the dependencies scope for other languages as well ?

**Comment by okou19900722** [comment]
@vietj add test scope?

**Comment by vietj** [comment]
yes if that's possible

**Comment by okou19900722** [comment]
It seems like that Lang implements of each language depends on its lib except kotlin and scala

**Comment by gmariotti** [comment]
Is this PR still relevant @okou19900722 and @vietj?

**Comment by vietj** [comment]
yes

**Comment by okou19900722** [comment]
The dependence of other languages is too strong. It seems that only kotlin has relatively few dependencies. Can we merge this pr first, making kotlin's dependencies simpler? As for other languages, we can discuss them again in issues.

**Comment by gmariotti** [comment]
This PR has been open for quite a while now, if nothing is blocking it, is it ok to merge it @vietj?

**Comment by vietj** [comment]
more a lack of attention

**Pull request merged**
