### PR TITLE
Invalid Kotlin translation for basic types

### LINKED ISSUE #29: Invalid Kotlin translation for basic types
Translated code does not compile if Java method returns short/byte/int/long/float/double/boolean/char or boxed equivalent.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #29

Special handling for Java primitives and boxed equivalent

### CODE REVIEW

**Review by vietj — CHANGES_REQUESTED** [review]
the various methods of MethodInvocation should be tested in MethodExpressionTest

**Comment by tsegismont** [comment]
@vietj I thought that the fact that it just compiles (it wouldn't before the change) would be enough. But fine will do.

**Comment by vietj** [comment]
it should be fine and new tests should be for all languages

**Comment by vietj** [comment]
what is the generated code when `someMethodWithBooleanReturn()` is called ?

**Comment by tsegismont** [comment]
@vietj as discussed off-list, tests are executed for all languages. See `io.vertx.codetrans.ConversionTestBase#runAll(java.lang.String, java.lang.String, java.lang.Runnable)`

The generated script is invoked and then checks run in `io.vertx.codetrans.MethodExpressionTest`

I just pushed a commit as agreed to cover all basic types in tests

**Review by vietj — APPROVED** [review]

**Pull request merged**
